# Generated by Django 4.0.5 on 2022-06-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imageURL',
            field=models.URLField(default='https://unsplash.com/es/fotos/j-udI4zim2E'),
        ),
    ]
