# Generated by Django 4.0.5 on 2022-06-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_category_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imageURL',
            field=models.URLField(default='https://images.unsplash.com/photo-1613575573097-15f53a39267a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'),
        ),
    ]
