# Generated by Django 4.0.5 on 2022-06-09 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_users_watchlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='users_watchlisted',
            field=models.ManyToManyField(related_name='watchlisted_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
